### ISSUE TITLE
Make role self contained without dependencies to others roles

### ISSUE THREAD

**Issue by BuhtigithuB** [robertdebock/ansible-role-xrdp#2]
It would be much easier if ansible-role-xrdp would not depends on 

 roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.epel
 
Either list the dependencies packages required or just copy over the other roles code in ansible-role-xrdp.

**Comment by robertdebock** [comment]
I like to break functionality up into these roles, as they are used for many other roles as well.
