### ISSUE TITLE
Typo in `defaults/main.yml`

### ISSUE THREAD

**Issue by 0kyn** [robertdebock/ansible-role-xrdp#4]
Hi @robertdebock,

It seems there's a typo in the default `xrdp_configuration` 
https://github.com/robertdebock/ansible-role-xrdp/blob/71abf898fd1d5e9f2ca1110f976e3b4344c4ccd8/defaults/main.yml#L4-L7

`option` should be `crypt_level` instead of `encrypt_level`

**Comment by robertdebock** [comment]
Super, I'll write a fix for it.
